config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "monitorings#index"

  resources :monitorings
  put "monitorings/switch_status/:id", to: "monitorings#switch_status", as: "switch_status"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can [:read], Monitoring
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monitoring.rb
class Monitoring < ApplicationRecord
  validates :service_title, :service_address, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/monitorings_controller.rb
class MonitoringsController < ApplicationController
  before_action :authenticate_user!

  def index
    @monitorings = Monitoring.all
  end

  def show
    @monitoring = Monitoring.find(params[:id])
  end

  def new
    @monitoring = Monitoring.new
  end

  def create
    @monitoring = Monitoring.new(monitoring_params)

    if @monitoring.save
      redirect_to @monitoring
    else
      render :new
    end
  end

  def edit
    @monitoring = Monitoring.find(params[:id])
  end

  def update
    @monitoring = Monitoring.find(params[:id])

    if @monitoring.update(monitoring_params)
      redirect_to @monitoring
    else
      render :edit
    end
  end

  def destroy
    @monitoring = Monitoring.find(params[:id])
    @monitoring.destroy

    redirect_to root_path
  end

  def switch_status
    @monitoring = Monitoring.find(params[:id])
    @monitoring.update(status: !@monitoring.status)
    @monitoring.update(warning_message: nil)

    redirect_to root_path
  end

  private

  def monitoring_params
    params.require(:monitoring).permit(:service_title, :service_address, :warning_message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ratatosk</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/monitorings/_form.html.erb

<div class="form-group">
  <%= form_with model: monitoring do |form| %>
    <div>
      <%= form.label "Título do Serviço" %><br>
      <%= form.text_field :service_title, :class => "form-control" %>
      <% monitoring.errors.full_messages_for(:service_title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label "Endereço do Serviço" %><br>
      <%= form.text_field :service_address, :class => "form-control" %><br>
      <% monitoring.errors.full_messages_for(:service_address).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label "Mensagem de Indisponibilidade (opcional)" %><br>
      <%= form.text_area :warning_message, :class => "form-control" %><br>
      <% monitoring.errors.full_messages_for(:warning_message).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    <div>
      <%= form.submit "Submeter" %>
    </div>
  <% end %>
</div>

app/views/monitorings/edit.html.erb
<div class="monitoring-info">
  <h1>Editar Monitoria</h1>

  <%= render "form", monitoring: @monitoring %>
</div>

app/views/monitorings/index.html.erb

<nav class="nav-index">
  <p>
    Logado como: <strong><%= current_user.email %></strong>.
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  </p>
</nav>

<div class="table-container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Serviço</th>
        <th scope="col">Endereço</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      <% @monitorings.each do |monitoring| %>
        <tr>
          <td scope="row"><%= link_to monitoring.service_title, monitoring %></td>
          <td scope="row"><%= link_to monitoring.service_address, monitoring %></td>
          <td scope="row">
            <% if monitoring.status? %>
              ✔️DISPONÍVEL
            <% else %>
              ❌INDISPONÍVEL
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<% if current_user.admin? %>
  <div class="button-area">
    <%= button_to "Nova Monitoria", new_monitoring_path, method: :get %>
  </div>
<% end %>

app/views/monitorings/new.html.erb
<div class="monitoring-info">
  <h1>Nova Monitoria</h1>

  <%= render "form", monitoring: @monitoring %>
</div>

app/views/monitorings/show.html.erb
<body>
  <div class="monitoring-info">
    <h1><strong><%= @monitoring.service_title %></strong></h1>
    <p><strong>Status</strong>: 
    <% if @monitoring.status? %>
      ✔️DISPONÍVEL
    <% else %>
      ❌INDISPONÍVEL
    <% end %>
    </p>
    <h5><%= link_to @monitoring.service_address, @monitoring.service_address %></h5>
    <% if !@monitoring.status %>
    <br>
      <p><strong>Motivo</strong>: <%= @monitoring.warning_message %></p>
    <% end %>
  </div>

  <% if can? :switch_status, Monitoring %>
    <div class="monitoring-admin-resources">
      <%= button_to "Alternar Status", switch_status_path(@monitoring), method: :put %>  
      <%= button_to "Editar", edit_monitoring_path(@monitoring), method: :get %>      
    </div>
  <% end %>

  <h6><%= link_to "Página Principal", root_path %><h6>
</body>